SELECT DISTINCT N'減容率マスタ' AS NAME FROM M_GENNYOURITSU WHERE HAIKI_NAME_CD IN /*HAIKI_NAME_CD*/('') AND DELETE_FLG = 'False'
UNION
SELECT DISTINCT N'マニフェスト換算マスタ' AS NAME FROM M_MANIFEST_KANSAN WHERE HAIKI_NAME_CD IN /*HAIKI_NAME_CD*/('') AND DELETE_FLG = 'False'