SELECT
UR.DELETE_FLG,
UR.GURUUPU_CD,
UR.GURUUPU_MEI,
UR.UPDATE_USER,
UR.UPDATE_DATE,
UR.CREATE_USER,
UR.CREATE_DATE,
UR.CREATE_PC,
UR.UPDATE_PC,
UR.TIME_STAMP,
UR.DENPYOU_KBN_CD
FROM
dbo.M_URIAGE UR
/*BEGIN*/WHERE
/*IF data.GURUUPU_CD != null*/CAST(UR.GURUUPU_CD AS varchar(3)) LIKE '%' + CAST(/*data.GURUUPU_CD*/0 AS varchar(3)) + '%'/*END*/
/*IF data.GURUUPU_MEI != null*/AND UR.GURUUPU_MEI LIKE '%' +  /*data.GURUUPU_MEI*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND UR.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, UR.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND UR.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, UR.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND UR.DELETE_FLG = /*deletechuFlg*/0/*END*/
/*IF !data.DENPYOU_KBN_CD.IsNull*/AND UR.DENPYOU_KBN_CD = /*data.DENPYOU_KBN_CD*/ /*END*/
/*END*/
ORDER BY UR.GURUUPU_CD
