SELECT
MGT.DELETE_FLG,
MGT.GENCHAKU_TIME_CD,
--quoc-begin
MGT.MOD_UNTEN_SHA,
MGT.MOD_WARIATE_JUN,
MGT.MOD_NYUURYOKU_TANTOUSHA,
MGT.MOD_NINI_TORI_FUKA,
MGT.MOD_RYUUBEI_KANZANKEISUU,
MGT.MOD_HAIKI_NAME_CD,
ISNULL(HAIKI.HAIKI_NAME,N'') AS MOD_HAIKI_NAME_RYAKU,
MGT.MOD_NISUGATA_CD,
ISNULL(NIS.NISUGATA_NAME_RYAKU,N'') AS MOD_NISUGATA_NAME_RYAKU,
MGT.MOD_SHOBUN_HOUHOU_CD,
ISNULL(SHO.SHOBUN_HOUHOU_NAME_RYAKU,N'') AS MOD_SHOBUN_HOUHOU_NAME_RYAKU,
MGT.MOD_GENYO_RITSU,
MGT.MOD_KYOBASHI,
--quoc-end
MGT.GENCHAKU_TIME_NAME,
MGT.GENCHAKU_TIME_NAME_RYAKU,
MGT.GENCHAKU_PRIORITY,
MGT.GENCHAKU_BACK_COLOR,
MGT.GENCHAKU_TIME_BIKOU,
MGT.UPDATE_USER,
MGT.UPDATE_DATE,
MGT.UPDATE_PC,
MGT.CREATE_USER,
MGT.CREATE_DATE,
MGT.CREATE_PC,
MGT.TIME_STAMP
FROM 
dbo.M_GENCHAKU_TIME MGT
LEFT JOIN dbo.M_HAIKI_NAME HAIKI ON MGT.MOD_HAIKI_NAME_CD = HAIKI.HAIKI_NAME_CD
LEFT JOIN dbo.M_NISUGATA NIS ON MGT.MOD_NISUGATA_CD = NIS.NISUGATA_CD
LEFT JOIN dbo.M_SHOBUN_HOUHOU SHO ON MGT.MOD_SHOBUN_HOUHOU_CD = SHO.SHOBUN_HOUHOU_CD
/*BEGIN*/WHERE
/*IF !data.GENCHAKU_TIME_CD.IsNull*/MGT.GENCHAKU_TIME_CD = /*data.GENCHAKU_TIME_CD*/ /*END*/
/*IF data.GENCHAKU_TIME_NAME != null*/AND MGT.GENCHAKU_TIME_NAME LIKE '%' +  /*data.GENCHAKU_TIME_NAME*/ + '%'/*END*/
/*IF data.GENCHAKU_TIME_NAME_RYAKU != null*/AND MGT.GENCHAKU_TIME_NAME_RYAKU LIKE '%' +  /*data.GENCHAKU_TIME_NAME_RYAKU*/ + '%'/*END*/
/*IF !data.GENCHAKU_PRIORITY.IsNull*/AND MGT.GENCHAKU_PRIORITY = /*data.GENCHAKU_PRIORITY*/ /*END*/
/*IF !data.GENCHAKU_BACK_COLOR.IsNull*/AND MGT.GENCHAKU_BACK_COLOR= /*data.GENCHAKU_BACK_COLOR*/ /*END*/
/*IF data.GENCHAKU_TIME_BIKOU != null*/AND MGT.GENCHAKU_TIME_BIKOU LIKE '%' +  /*data.GENCHAKU_TIME_BIKOU*/ + '%'/*END*/
/*IF data.CREATE_USER != null*/AND MGT.CREATE_USER LIKE '%' +  /*data.CREATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_CREATE_DATE != null*/AND CONVERT(nvarchar, MGT.CREATE_DATE, 120) LIKE '%' +  /*data.SEARCH_CREATE_DATE*/ + '%'/*END*/
/*IF data.UPDATE_USER != null*/AND MGT.UPDATE_USER LIKE '%' +  /*data.UPDATE_USER*/ + '%'/*END*/
/*IF data.SEARCH_UPDATE_DATE != null*/AND CONVERT(nvarchar, MGT.UPDATE_DATE, 120) LIKE '%' +  /*data.SEARCH_UPDATE_DATE*/ + '%'/*END*/
/*IF !deletechuFlg*/AND MGT.DELETE_FLG = /*deletechuFlg*/0/*END*/
--quoc-begin
/*IF !data.MOD_WARIATE_JUN.IsNull*/AND MGT.MOD_WARIATE_JUN = /*data.MOD_WARIATE_JUN*/ /*END*/
/*IF !data.MOD_UNTEN_SHA.IsNull*/AND MGT.MOD_UNTEN_SHA = /*data.MOD_UNTEN_SHA*/ /*END*/
/*IF !data.MOD_NYUURYOKU_TANTOUSHA.IsNull*/AND MGT.MOD_NYUURYOKU_TANTOUSHA = /*data.MOD_NYUURYOKU_TANTOUSHA*/ /*END*/
/*IF !data.MOD_NINI_TORI_FUKA.IsNull*/AND MGT.MOD_NINI_TORI_FUKA = /*data.MOD_NINI_TORI_FUKA*/ /*END*/
/*IF !data.MOD_RYUUBEI_KANZANKEISUU.IsNull*/MGT.MOD_RYUUBEI_KANZANKEISUU = /*data.MOD_RYUUBEI_KANZANKEISUU*/ /*END*/
--quoc-end
/*END*/
/*END*/
ORDER BY MGT.GENCHAKU_TIME_CD